# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/Mel-GitHub/redis-golang-app
    environment:
      DOCKER_USER: melcheng  
      STABLE_RELEASE: v0.1
    steps:
      - checkout
      - run: # print the name of the branch we're on
          name: "What is the CIRCLE_BUILD_NUM?"
          command: echo ${CIRCLE_BUILD_NUM}
      - run: 
          name: Get all dependencies
          command: |
            go get -v -t -d ./...
            go get -u github.com/gomodule/redigo/redis
            go get -u github.com/rs/zerolog/log
            go get -u github.com/rs/zerolog
      - setup_remote_docker
            # docker_layer_caching: true
      - run:
          name: Build and push Docker images
          command: |
            docker build -t ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:${STABLE_RELEASE}.${CIRCLE_BUILD_NUM} .
            docker images  
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:${STABLE_RELEASE}.${CIRCLE_BUILD_NUM}
      - run:
          name: Update Github deployment 
          command: |
            ### sed -i "s/${STABLE_RELEASE}.${CIRCLE_PREVIOUS_BUILD_NUM}/${STABLE_RELEASE}.${CIRCLE_BUILD_NUM}/g" ${CIRCLE_WORKING_DIRECTORY}/deploy/redis-golang-app-deploy.yml
            sed -i "s/v[0-9]*\.[0-9]*\.[0-9]*/${STABLE_RELEASE}.${CIRCLE_BUILD_NUM}/g" ${CIRCLE_WORKING_DIRECTORY}/deploy/redis-golang-app-deploy.yml
            cat ${CIRCLE_WORKING_DIRECTORY}/deploy/redis-golang-app-deploy.yml
            git version
            git config --global user.email "bot@circleci.com"
            git config --global user.name "Deployment Bot"
            git add .
            git commit -m "Update via CircleCI"
            # Push quietly to prevent showing the token in log
            git push -q https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git ${CIRCLE_BRANCH}
    ####  - run: go test -v ./...
