apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-golang
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: redis-golang
  template:
    metadata:
      labels:
        app: redis-golang
    spec:
      containers:
        - image: melcheng/redis-golang-app:v0.1.48
          name: redis-golang
          ports:
            - containerPort: 8081
          imagePullPolicy: Always
          # The probe
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 2