apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: redis-node
  labels:
    app: redis-node
spec:
  selector:
    matchLabels:
      app: redis-node
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-node
    spec:
      containers:
      - name: master
        image: k8s.gcr.io/redis:e2e  # or just image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 300m
            memory: 300Mi
        ports:
        - containerPort: 6379
